Fix GithubProvider scope settings
nextauthjs/next-auth-example pull request #50
Opened 2021-12-30 11:58 UTC by schoenwaldnils

2021-12-30 15:54 UTC, balazsorban44 requested changes
This setting can be dropped. The default scope is the same as defined here.

2021-12-31 09:59 UTC, schoenwaldnils commented
Since this is an example project I'd prefer to keep it in here (maybe with another scope?) or take it out and have the documentation for the provider updated.
I had to search through other issues to find the right way to change the scope. (Also because the type definition of the provider options are not clear)

2021-12-31 11:12 UTC, balazsorban44 commented
For that, please refer to the documentation

https://next-auth.js.org/providers/github

https://next-auth.js.org/configuration/providers/oauth#authorization-option

2022-01-01 22:49 UTC, balazsorban44 requested changes

2022-01-01 22:49 UTC, balazsorban44 commented on pages/api/auth/[...nextauth].js
> +      },
```suggestion
```

2022-01-03 14:02 UTC, merged