feat: Make appDir default as stable since Next.js 13
nextauthjs/next-auth-example pull request #86
Opened 2023-06-07 18:26 UTC by jrobsontull

Since the new app router was made stable in Next.js 13, we should consider making this the default way to initialise `next-auth` within projects. I had to spend some time learning how to integrate the `/app` directory with `next-auth` and I think a full working example repository would be really helpful.

It is probably worth maintaining the current `/pages` example repository since support for this will not be going away anytime soon and most codebases likely make use of this version of the Next.js router.

I know that there is an existing [next-13-auth-app](https://github.com/balazsorban44/nextjs-13-next-auth-app) repository but I could not find a link to this in the documentation. I still think it would be good to maintain a similar repository as the current `next-auth-example` to make it easier for users to migrate and for new users to understand how to integrate `next-auth` fully with Next.js 13. Perhaps we need an official `next-auth-next-13-example`?

2023-06-14 13:07 UTC, DougInAMug commented
Thanks for bring that repo to my attention @jrobsontull ! Whether or not it's default, would be very useful to have more prominently linked in main docs.

2023-06-16 00:27 UTC, bourgeois247 commented
Thank you @jrobsontull, your PR saved me from the nightmare trying to figure out what I was doing wrong. I had an inkling that it had to do with `route.ts` somehow, but you PR clarified exactly how to make the changes.

2023-06-20 11:40 UTC, pedroapfilho commented
This PR deserves its own repo IMO, something like `next-auth-appdir`

2023-06-20 11:52 UTC, jrobsontull commented
> This PR deserves its own repo IMO, something like `next-auth-appdir`

@pedroapfilho Given the fact that people are still confused in the [original PR](https://github.com/nextauthjs/next-auth/pull/6777) and [issue/discussio](https://github.com/nextauthjs/next-auth/issues/6792)n for route handler support, I think this is probably the best approach.

@balazsorban44 any thoughts on this?

2023-07-08 15:51 UTC, philip-ulrich commented
Also wanted to pop in and say thanks for this. Should probably just get merged. 😆

2023-07-21 03:05 UTC, ImBIOS requested changes

2023-07-21 03:05 UTC, ImBIOS commented on package.json
> +    "next": "^13.4.5",
I recommend to using 'latest' for project with context as example, and let the exact version saved in the lockfile.

2023-07-21 04:14 UTC, ImBIOS commented on lib/auth/AuthProvider.tsx
> +  return <SessionProvider>{children}</SessionProvider>;
Where is the session passed to SessionProvider?

2023-09-03 16:56 UTC, balazsorban44 commented
Closing as per the README https://github.com/nextauthjs/next-auth-example#readme

2023-09-03 16:56 UTC, closed without merging